{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a506cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Get token.",
        "uid" : "38e1e7dbeee8c30f",
        "parentUid" : "78842d3add8ada5d0d07d6f782dbd5e0",
        "status" : "broken",
        "time" : {
          "start" : 1723670496685,
          "stop" : 1723670496685,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "78842d3add8ada5d0d07d6f782dbd5e0"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4522cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Complex",
        "uid" : "f4cfa1317c9b105d",
        "parentUid" : "3f138cce742fc86408761f7ddc7e4aa0",
        "status" : "broken",
        "time" : {
          "start" : 1723670666210,
          "stop" : 1723670666339,
          "duration" : 129
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "3f138cce742fc86408761f7ddc7e4aa0"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /get_profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a506d790>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Capacity_db",
        "uid" : "4af71af0c3eccb",
        "parentUid" : "86616eaa2debea12979c7b53d57ae9a5",
        "status" : "broken",
        "time" : {
          "start" : 1723670666485,
          "stop" : 1723670666699,
          "duration" : 214
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "86616eaa2debea12979c7b53d57ae9a5"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4523c50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "Get token.",
        "uid" : "25a2025c48d7075b",
        "parentUid" : "21f25cb7dc3ff7a8dd6496b485398d4f",
        "status" : "broken",
        "time" : {
          "start" : 1723670666813,
          "stop" : 1723670666813,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "21f25cb7dc3ff7a8dd6496b485398d4f"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /tos (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a416b0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET tos.",
        "uid" : "b8d4adf7e017b283",
        "parentUid" : "119a140f31e19987b0c908c805b750da",
        "status" : "broken",
        "time" : {
          "start" : 1723670667211,
          "stop" : 1723670667438,
          "duration" : 227
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "119a140f31e19987b0c908c805b750da"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /get_profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a41488c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET profile information.",
        "uid" : "6afc3b7a0907165b",
        "parentUid" : "0f948f1c24b8f99d75e47c35188233f8",
        "status" : "broken",
        "time" : {
          "start" : 1723670667557,
          "stop" : 1723670667664,
          "duration" : 107
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "0f948f1c24b8f99d75e47c35188233f8"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /list_dbtypes (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a414b230>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET list list_dbtypes.",
        "uid" : "d1e2cddce831557c",
        "parentUid" : "ee894506cca3581a802d32dc6362a2ec",
        "status" : "broken",
        "time" : {
          "start" : 1723670667780,
          "stop" : 1723670667887,
          "duration" : 107
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "ee894506cca3581a802d32dc6362a2ec"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /list_dbversions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4179100>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET list db_versions.",
        "uid" : "11b8659418b07c3f",
        "parentUid" : "6f1113edc63dc692230b15eb4748cf53",
        "status" : "broken",
        "time" : {
          "start" : 1723670668002,
          "stop" : 1723670668108,
          "duration" : 106
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "6f1113edc63dc692230b15eb4748cf53"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /list_dbenvs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a417a780>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET list list_dbenvs.",
        "uid" : "c6bc9783236845db",
        "parentUid" : "ad2aa6e6b6ac9b6d28689dd18b4ec547",
        "status" : "broken",
        "time" : {
          "start" : 1723670668226,
          "stop" : 1723670668319,
          "duration" : 93
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "ad2aa6e6b6ac9b6d28689dd18b4ec547"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /list_regions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a41af410>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET list list_regions.",
        "uid" : "1243c13dee875832",
        "parentUid" : "b169bbb0f8a0a49f2456f2f12d6be549",
        "status" : "broken",
        "time" : {
          "start" : 1723670668438,
          "stop" : 1723670668546,
          "duration" : 108
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "b169bbb0f8a0a49f2456f2f12d6be549"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /bad_request (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a41af7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET bad_request.",
        "uid" : "7eacd35c42f046ec",
        "parentUid" : "1dc7e372c3492dd37f65901c2a6c327d",
        "status" : "broken",
        "time" : {
          "start" : 1723670668666,
          "stop" : 1723670668774,
          "duration" : 108
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "1dc7e372c3492dd37f65901c2a6c327d"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /get_profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a412ede0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "GET profile status.",
        "uid" : "668096a136a1471d",
        "parentUid" : "f1cd511ca1e9bd61e7b0e86b9681fbc1",
        "status" : "broken",
        "time" : {
          "start" : 1723670668890,
          "stop" : 1723670669011,
          "duration" : 121
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "f1cd511ca1e9bd61e7b0e86b9681fbc1"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a412fad0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "test_get_token_and_body",
        "uid" : "5b79913a2e4a4bb5",
        "parentUid" : "acca25d70f3e9b540e880e1a906fe9b1",
        "status" : "broken",
        "time" : {
          "start" : 1723670669131,
          "stop" : 1723670669131,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "acca25d70f3e9b540e880e1a906fe9b1"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4176f30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration for English language.",
        "uid" : "b9b4f30c45e886ad",
        "parentUid" : "51550d8581970b80c0e3115f322013c5",
        "status" : "broken",
        "time" : {
          "start" : 1723670669536,
          "stop" : 1723670669633,
          "duration" : 97
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "51550d8581970b80c0e3115f322013c5"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a418b5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration for English language not agree.",
        "uid" : "c5694c9ebdcaba67",
        "parentUid" : "2aba8437914a2473e59da8f2c23a94b8",
        "status" : "broken",
        "time" : {
          "start" : 1723670669754,
          "stop" : 1723670669850,
          "duration" : 96
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "2aba8437914a2473e59da8f2c23a94b8"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a418b170>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration Bulgaria language.",
        "uid" : "bafd5aa785797104",
        "parentUid" : "227750466533853ffefcdf2223913d7c",
        "status" : "broken",
        "time" : {
          "start" : 1723670669972,
          "stop" : 1723670670079,
          "duration" : 107
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "227750466533853ffefcdf2223913d7c"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3ef29c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration Bulgaria language not agree.",
        "uid" : "b1e2f69fb3e83b57",
        "parentUid" : "32ae48f221b53a22c786d543d5b4db14",
        "status" : "broken",
        "time" : {
          "start" : 1723670670202,
          "stop" : 1723670670305,
          "duration" : 103
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "32ae48f221b53a22c786d543d5b4db14"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a418bc20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration email is taken for en-us",
        "uid" : "8b0d68dadc3b6972",
        "parentUid" : "6b3c3c2543bd4b2ff9123cec9d163508",
        "status" : "broken",
        "time" : {
          "start" : 1723670670453,
          "stop" : 1723670670547,
          "duration" : 94
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "6b3c3c2543bd4b2ff9123cec9d163508"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a412cfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration email is taken for bg-bg",
        "uid" : "6e12f9fe295a3872",
        "parentUid" : "caf2ee0594884e8faeb15f24d7dedc97",
        "status" : "broken",
        "time" : {
          "start" : 1723670670667,
          "stop" : 1723670670775,
          "duration" : 108
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "caf2ee0594884e8faeb15f24d7dedc97"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a41af830>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST registration email is taken for unsupported languages",
        "uid" : "ed12f4e56af9b3ca",
        "parentUid" : "9f6aac7ea720d01adab5fddea048f451",
        "status" : "broken",
        "time" : {
          "start" : 1723670670897,
          "stop" : 1723670670992,
          "duration" : 95
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "9f6aac7ea720d01adab5fddea048f451"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a417b1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST login",
        "uid" : "48d74b0165b1d106",
        "parentUid" : "b32829684741b5f5af7aee5129373dca",
        "status" : "broken",
        "time" : {
          "start" : 1723670671122,
          "stop" : 1723670671218,
          "duration" : 96
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "b32829684741b5f5af7aee5129373dca"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /is_logged (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a416ade0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST is logged",
        "uid" : "11510237fcb9c12b",
        "parentUid" : "c4b7012ae8baa40d8e20bcddb4dc4da9",
        "status" : "broken",
        "time" : {
          "start" : 1723670671349,
          "stop" : 1723670671444,
          "duration" : 95
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "c4b7012ae8baa40d8e20bcddb4dc4da9"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /is_logged (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4520740>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST is_logged_with_wrong_token",
        "uid" : "f4ca2ce7802b4b41",
        "parentUid" : "29e076191cd89a2f5dd8063ce44c3e35",
        "status" : "broken",
        "time" : {
          "start" : 1723670671565,
          "stop" : 1723670671675,
          "duration" : 110
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "29e076191cd89a2f5dd8063ce44c3e35"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4522b70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST is logout",
        "uid" : "26d7941ed27d1ca7",
        "parentUid" : "9d5be3de945d5439baba958965105194",
        "status" : "broken",
        "time" : {
          "start" : 1723670671796,
          "stop" : 1723670671904,
          "duration" : 108
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "9d5be3de945d5439baba958965105194"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3e753d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST login/is_logged/logout",
        "uid" : "5c2eaea83f03435a",
        "parentUid" : "5cf6c24b11616256107be2640bd52946",
        "status" : "broken",
        "time" : {
          "start" : 1723670672023,
          "stop" : 1723670672023,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "5cf6c24b11616256107be2640bd52946"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3fe3e30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST logout with wrong logout token",
        "uid" : "4319eeca5cdadb14",
        "parentUid" : "dcf039de2020e40ada20746e6c8d38b5",
        "status" : "broken",
        "time" : {
          "start" : 1723670672514,
          "stop" : 1723670672514,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "dcf039de2020e40ada20746e6c8d38b5"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3fe1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_create",
        "uid" : "f57cc9da558452b",
        "parentUid" : "228f75eef15415ab7f6d97a65b0a6f2e",
        "status" : "broken",
        "time" : {
          "start" : 1723670672886,
          "stop" : 1723670672886,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "228f75eef15415ab7f6d97a65b0a6f2e"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3f1e030>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_create_with_wrong_db_type.",
        "uid" : "9053fd9ed880fd8b",
        "parentUid" : "16267a1e5f230cf6a25bc783d4d9d995",
        "status" : "broken",
        "time" : {
          "start" : 1723670673257,
          "stop" : 1723670673355,
          "duration" : 98
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "16267a1e5f230cf6a25bc783d4d9d995"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3f22e40>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_create_with_wrong_db_version.",
        "uid" : "c9349733f7473726",
        "parentUid" : "078da221a0db8dabf0c495a5ad024b4c",
        "status" : "broken",
        "time" : {
          "start" : 1723670673479,
          "stop" : 1723670673693,
          "duration" : 214
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "078da221a0db8dabf0c495a5ad024b4c"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3f21820>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_create_with_wrong_env.",
        "uid" : "d7eb51ebf7ce3285",
        "parentUid" : "85103ee9ba16657504d9cad32f93b857",
        "status" : "broken",
        "time" : {
          "start" : 1723670673814,
          "stop" : 1723670693326,
          "duration" : 19512
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "85103ee9ba16657504d9cad32f93b857"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3f22f30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_create_with_wrong_region.",
        "uid" : "d736614a7cc57c27",
        "parentUid" : "294cf0116a25e8cd4e317cca504b7285",
        "status" : "broken",
        "time" : {
          "start" : 1723670693446,
          "stop" : 1723670693543,
          "duration" : 97
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "294cf0116a25e8cd4e317cca504b7285"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /db_list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3f78620>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST db_list",
        "uid" : "a48e3eace4d04f12",
        "parentUid" : "3cd509e80c01f3320c857b21683a9d47",
        "status" : "broken",
        "time" : {
          "start" : 1723670693666,
          "stop" : 1723670693762,
          "duration" : 96
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "3cd509e80c01f3320c857b21683a9d47"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a40c1460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST create_docker_container",
        "uid" : "a89823b7c7f06d84",
        "parentUid" : "6520933b9627b4d18e4483bc28a8d192",
        "status" : "broken",
        "time" : {
          "start" : 1723670693886,
          "stop" : 1723670693982,
          "duration" : 96
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "6520933b9627b4d18e4483bc28a8d192"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /password_update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3e77620>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST change_password",
        "uid" : "aea5e5e530981bc5",
        "parentUid" : "dc4399194818783d5ea615c8acfba7c5",
        "status" : "broken",
        "time" : {
          "start" : 1723670694338,
          "stop" : 1723670694435,
          "duration" : 97
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "dc4399194818783d5ea615c8acfba7c5"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /password_update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3fe1010>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST change_password_with_wrong_data",
        "uid" : "dc6bdc92daae7672",
        "parentUid" : "a9c9b476b064a6048b9a4a011a9ec985",
        "status" : "broken",
        "time" : {
          "start" : 1723670694559,
          "stop" : 1723670694673,
          "duration" : 114
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "a9c9b476b064a6048b9a4a011a9ec985"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /password_update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4522b40>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST change_password_without_token",
        "uid" : "609ccf40fd285062",
        "parentUid" : "3fa4d419ccc23c9788330711783e8c70",
        "status" : "broken",
        "time" : {
          "start" : 1723670694796,
          "stop" : 1723670695012,
          "duration" : 216
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "3fa4d419ccc23c9788330711783e8c70"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a4178380>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST create_docker_container",
        "uid" : "9fa827eee400cdf6",
        "parentUid" : "60d9d6b2b3119f627bc21b216516dd25",
        "status" : "broken",
        "time" : {
          "start" : 1723670695136,
          "stop" : 1723670695231,
          "duration" : 95
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "60d9d6b2b3119f627bc21b216516dd25"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a3ef19a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST checking ports_len positive",
        "uid" : "130a8c5f133e0abf",
        "parentUid" : "d4bda1ebb2b172ee3641e36173cb0bed",
        "status" : "broken",
        "time" : {
          "start" : 1723670695352,
          "stop" : 1723670695447,
          "duration" : 95
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "d4bda1ebb2b172ee3641e36173cb0bed"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a40c2150>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST checking ports_len negative range",
        "uid" : "bb1eaa0c81fff4f9",
        "parentUid" : "5f07671c958b1e7e64ed950005fe1c1f",
        "status" : "broken",
        "time" : {
          "start" : 1723670695572,
          "stop" : 1723670695668,
          "duration" : 96
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "5f07671c958b1e7e64ed950005fe1c1f"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a40c2870>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST checking ports_len negative len",
        "uid" : "efb15244f71a90b3",
        "parentUid" : "ef9550c76207ead2108baa7500909616",
        "status" : "broken",
        "time" : {
          "start" : 1723670695789,
          "stop" : 1723670696007,
          "duration" : 218
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "ef9550c76207ead2108baa7500909616"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a40e8b30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST checking ports_len negative symbols",
        "uid" : "80692182de0bea7d",
        "parentUid" : "9bc1ab4894bc3908097697fbdbcfa7c9",
        "status" : "broken",
        "time" : {
          "start" : 1723670696128,
          "stop" : 1723670696258,
          "duration" : 130
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "9bc1ab4894bc3908097697fbdbcfa7c9"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dbend.areso.pro', port=443): Max retries exceeded with url: /container_create (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64a40e97c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "POST create_docker_container_without_token",
        "uid" : "ccf3cc4bce93883c",
        "parentUid" : "d246276a7e5b20b61e0cbca3e07445da",
        "status" : "broken",
        "time" : {
          "start" : 1723670696378,
          "stop" : 1723670696476,
          "duration" : 98
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "d246276a7e5b20b61e0cbca3e07445da"
    }, {
      "name" : "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)",
      "children" : [ {
        "name" : "POST create_docker_container_without_token",
        "uid" : "e5ae715a5eccf187",
        "parentUid" : "0deff55915d4c9ebc746eac29285817c",
        "status" : "broken",
        "time" : {
          "start" : 1723670696597,
          "stop" : 1723670696880,
          "duration" : 283
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      }, {
        "name" : "POST delete_container",
        "uid" : "4da032926d0aabfb",
        "parentUid" : "0deff55915d4c9ebc746eac29285817c",
        "status" : "broken",
        "time" : {
          "start" : 1723670696934,
          "stop" : 1723670697217,
          "duration" : 283
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      }, {
        "name" : "Get token.",
        "uid" : "2cd2852c2f00834c",
        "parentUid" : "0deff55915d4c9ebc746eac29285817c",
        "status" : "broken",
        "time" : {
          "start" : 1723670729443,
          "stop" : 1723670729443,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "0deff55915d4c9ebc746eac29285817c"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@id=\"menu_button_status\"]')\nStacktrace:\n#0 0x56405ac766aa <unknown>\n#1 0x56405a947600 <unknown>\n#2 0x56405a996bcb <unknown>\n#3 0x56405a996eb1 <unknown>\n#4 0x56405a9dab24 <unknown>\n#5 0x56405a9b98cd <unknown>\n#6 0x56405a9d804a <unknown>\n#7 0x56405a9b9643 <unknown>\n#8 0x56405a989d31 <unknown>\n#9 0x56405a98a79e <unknown>\n#10 0x56405ac3e23b <unknown>\n#11 0x56405ac421d2 <unknown>\n#12 0x56405ac2b5f5 <unknown>\n#13 0x56405ac42d62 <unknown>\n#14 0x56405ac1023f <unknown>\n#15 0x56405ac65e48 <unknown>\n#16 0x56405ac66020 <unknown>\n#17 0x56405ac7547c <unknown>\n#18 0x7fee8d294ac3 <unknown>",
      "children" : [ {
        "name" : "test_create_database",
        "uid" : "b74041edf802e46b",
        "parentUid" : "7caa748e0b2572b00b3d3c2fd423b8a7",
        "status" : "broken",
        "time" : {
          "start" : 1723670732044,
          "stop" : 1723670738181,
          "duration" : 6137
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "7caa748e0b2572b00b3d3c2fd423b8a7"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find elements by locator ('xpath', '//tbody[@id=\"tbody_dbs\"]/tr')",
      "children" : [ {
        "name" : "test_delete_database",
        "uid" : "4a3fdaca40e7d812",
        "parentUid" : "e156df9511dbef675f6228c9996192c5",
        "status" : "broken",
        "time" : {
          "start" : 1723670739015,
          "stop" : 1723670746671,
          "duration" : 7656
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "e156df9511dbef675f6228c9996192c5"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find elements by locator ('xpath', '//tbody[@id=\"tbody_dbs\"]//tr')",
      "children" : [ {
        "name" : "test_clipboard",
        "uid" : "8dec1e1f761c194",
        "parentUid" : "b942fddcb4d57cbcfa2fa615fa55900e",
        "status" : "broken",
        "time" : {
          "start" : 1723670747534,
          "stop" : 1723670754409,
          "duration" : 6875
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "b942fddcb4d57cbcfa2fa615fa55900e"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@id = \"menu_button_databases\"]')\nStacktrace:\n#0 0x558bed19d6aa <unknown>\n#1 0x558bece6e600 <unknown>\n#2 0x558becebdbcb <unknown>\n#3 0x558becebdeb1 <unknown>\n#4 0x558becf01b24 <unknown>\n#5 0x558becee08cd <unknown>\n#6 0x558beceff04a <unknown>\n#7 0x558becee0643 <unknown>\n#8 0x558beceb0d31 <unknown>\n#9 0x558beceb179e <unknown>\n#10 0x558bed16523b <unknown>\n#11 0x558bed1691d2 <unknown>\n#12 0x558bed1525f5 <unknown>\n#13 0x558bed169d62 <unknown>\n#14 0x558bed13723f <unknown>\n#15 0x558bed18ce48 <unknown>\n#16 0x558bed18d020 <unknown>\n#17 0x558bed19c47c <unknown>\n#18 0x7fc606494ac3 <unknown>",
      "children" : [ {
        "name" : "test_clipboard_jdbc",
        "uid" : "3241635415f6a187",
        "parentUid" : "969023b65e165225c6b5730d5c662b02",
        "status" : "broken",
        "time" : {
          "start" : 1723670755247,
          "stop" : 1723670760379,
          "duration" : 5132
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "969023b65e165225c6b5730d5c662b02"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//button[@id=\"menu_button_containers\"]')\nStacktrace:\n#0 0x55de821546aa <unknown>\n#1 0x55de81e25600 <unknown>\n#2 0x55de81e74bcb <unknown>\n#3 0x55de81e74eb1 <unknown>\n#4 0x55de81eb8b24 <unknown>\n#5 0x55de81e978cd <unknown>\n#6 0x55de81eb604a <unknown>\n#7 0x55de81e97643 <unknown>\n#8 0x55de81e67d31 <unknown>\n#9 0x55de81e6879e <unknown>\n#10 0x55de8211c23b <unknown>\n#11 0x55de821201d2 <unknown>\n#12 0x55de821095f5 <unknown>\n#13 0x55de82120d62 <unknown>\n#14 0x55de820ee23f <unknown>\n#15 0x55de82143e48 <unknown>\n#16 0x55de82144020 <unknown>\n#17 0x55de8215347c <unknown>\n#18 0x7f8d2b894ac3 <unknown>",
      "children" : [ {
        "name" : "test_clipboard_uuid_docker",
        "uid" : "337918a9f35a8326",
        "parentUid" : "b3242d0bad4d1c6f3622faddf4278951",
        "status" : "broken",
        "time" : {
          "start" : 1723670761234,
          "stop" : 1723670766369,
          "duration" : 5135
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "b3242d0bad4d1c6f3622faddf4278951"
    }, {
      "name" : "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//div[@id=\"msg_from_server\"]')",
      "children" : [ {
        "name" : "test_create_docker_container",
        "uid" : "d26388b5d6e94eb4",
        "parentUid" : "3ade11a03a0ed1fd0050f9b450596951",
        "status" : "broken",
        "time" : {
          "start" : 1723670767219,
          "stop" : 1723670783462,
          "duration" : 16243
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "3ade11a03a0ed1fd0050f9b450596951"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  }, {
    "name" : "Product defects",
    "children" : [ {
      "name" : "AssertionError",
      "children" : [ {
        "name" : "test_delete_container",
        "uid" : "eb217cf417fd2656",
        "parentUid" : "a0017ad855102fea08b8682d27fec4ca",
        "status" : "failed",
        "time" : {
          "start" : 1723670784329,
          "stop" : 1723670802964,
          "duration" : 18635
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "a0017ad855102fea08b8682d27fec4ca"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ],
  "name" : "categories"
}